name: Ну сколько можно

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Туда-сюда проверка
      uses: actions/checkout@v2

    - name: Супер-супер-супер-супер линетр
      uses: github/super-linter@v5
